package com.buyer.dto.magicpin;

public enum Status {

    SUCCESS, FAILURE, ACCEPTED, DISPATCH_READY, DISPATCHED, MERCHANT_DELIVERED, CANCELLED, UNAVAILABLE,
    AVAILABLE, ASSIGNED, REACHED_MERCHANT, PICKED_UP, REACHED_CUSTOMER, DELIVERED, success, failed, Failed, Success

}
