package com.buyer.entity.PaymentEnum;

public enum PaymentMode {
    ONLINE, COD, WALLET, JUSPAY, GOOGLE_OFFER, FM_WALLET, SIMPL, GOOGLE_ONLINE, AUTO_DEBIT, LAZYPAY, ZETA, AMAZON_PAY, PHONEPE, FM_WALLET_PROMO, RAZORPAY, SODEXO, PAYTM, CORPORATE_CREDIT, UPI, PAYPAL, ORDER_UPDATE, ZOMATO_COD,
    PHONEPE_AFFILIATE,AMAZON_PAY_AFFILIATE,DAILY_NINJA,QWIK_SILVER,PAYTM_POSTPAID,PAYZAPP,PHONEPE_WANDERCRUST_AFFILIATE,
    PAYTM_AFFILIATE,PAYTM_WANDERCRUST_AFFILIATE,TWID_AFFILIATE,MIPAY,GOKHANA,TWID_PAY,WHATSAPP,MAGIC_PIN,DOTPE;
}
