package com.buyer.entity.PaymentEnum;

public enum PaymentGateway {
    PAYU, CITRUS, MANUAL, INTUIT_WALLET, PAYTM_WALLET, MOBIKWIK_WALLET, PAYUW, WALLET, FREECHARGE_WALLET, CITRUS_WALLET, MAGIC_TIGER, SIMPL, JUSPAY, FRESH_MONEY, MIND_IQ, HELP_CHAT, RUNNR, FRESHMENU, THIRD_PARTY, HUNGER_BOX, UBER_EATS, LAZYPAY, AMAZON_PAY, RAZORPAY, PHONEPE, PAYTM_POS, SODEXO, UPI, GOOGLE_TEZ, PAYTM_UPI,
    PAYPAL,
    RAZORPAY_UPI, ZOMATO, MAGIC_PIN,
    PHONEPE_AFFILIATE,
    AMAZON_PAY_AFFILIATE,
    PAYZAPP,QWIK_SILVER,
    PAYTM_POSTPAID,
    PHONEPE_WANDERCRUST_AFFILIATE,
    PAYTM_AFFILIATE,
    PAYTM_WANDERCRUST_AFFILIATE,
    TWID_AFFILIATE,
    MIPAY,
    GOOGLE_PAY_SPOT,
    PAYZAPP_AFFILIATE,
    GOKHANA,
    TWID_PAY,
    WHATSAPP,
    BULK_ORDER,
    POS,
    CORPORATE_ORDER,
    BITSILA_ONDC,
    FALCONS;
}
