package com.buyer.entity;

public enum OrderAdditionalData {
    ZOMATO_ORDER_ID,
    ORDER_AMOUNT_BALANCE,
    ORDER_AMOUNT_PAID,
    ORDER_NET_AMOUNT,
    ORDER_GROSS_AMOUNT,
    ORDER_DISCOUNT_AMOUNT,
    ZOMATO_OTP,
    ORDER_OFFER_COUPON,
    DELIVERY_CHANNEL,
    IS_QVM_ORDER,
    NOTES,
    EXPECTED_KITCHEN_ID,
    IS_EXPRESS_CHECK_OUT
}
